const { DataTypes } = require('sequelize');
function createModels(sequelize) {
  const Department = sequelize.define('Department', { id: { type: DataTypes.INTEGER, primaryKey: true, field: 'ID' }, name: { type: DataTypes.STRING(100), allowNull: false, field: 'NAME' }, short_code: { type: DataTypes.STRING(10), field: 'SHORT_CODE' }, head_doctor_id: { type: DataTypes.INTEGER, field: 'HEAD_DOCTOR_ID' }, floor_location: { type: DataTypes.STRING(50), field: 'FLOOR_LOCATION' }, is_active: { type: DataTypes.CHAR(1), field: 'IS_ACTIVE' } }, { tableName: 'HMS_DEPARTMENTS', freezeTableName: true, timestamps: false });
  const Doctor = sequelize.define('Doctor', { id: { type: DataTypes.INTEGER, primaryKey: true, field: 'ID' }, user_id: { type: DataTypes.INTEGER, allowNull: false, field: 'USER_ID' }, department_id: { type: DataTypes.INTEGER, field: 'DEPARTMENT_ID' }, speciality: { type: DataTypes.STRING(100), field: 'SPECIALITY' }, registration_number: { type: DataTypes.STRING(50), field: 'REGISTRATION_NUMBER' }, fee: { type: DataTypes.DECIMAL(10, 2), field: 'FEE' }, slot_duration_mins: { type: DataTypes.INTEGER, field: 'SLOT_DURATION_MINS' }, is_active: { type: DataTypes.CHAR(1), field: 'IS_ACTIVE' } }, { tableName: 'HMS_DOCTORS', freezeTableName: true, timestamps: false });
  const Appointment = sequelize.define('Appointment', { id: { type: DataTypes.INTEGER, primaryKey: true, field: 'ID' }, patient_id: { type: DataTypes.INTEGER, allowNull: false, field: 'PATIENT_ID' }, doctor_id: { type: DataTypes.INTEGER, allowNull: false, field: 'DOCTOR_ID' }, department_id: { type: DataTypes.INTEGER, allowNull: false, field: 'DEPARTMENT_ID' }, appointment_date: { type: DataTypes.DATEONLY, allowNull: false, field: 'APPOINTMENT_DATE' }, slot_start: { type: DataTypes.STRING(10), field: 'SLOT_START' }, slot_end: { type: DataTypes.STRING(10), field: 'SLOT_END' }, appt_type: { type: DataTypes.STRING(20), field: 'APPT_TYPE' }, status: { type: DataTypes.STRING(20), field: 'STATUS' }, cancellation_reason: { type: DataTypes.STRING(500), field: 'CANCELLATION_REASON' }, booked_by: { type: DataTypes.INTEGER, field: 'BOOKED_BY' } }, { tableName: 'HMS_APPOINTMENTS', freezeTableName: true, timestamps: false });
  const Token = sequelize.define('Token', { id: { type: DataTypes.INTEGER, primaryKey: true, field: 'ID' }, patient_id: { type: DataTypes.INTEGER, allowNull: false, field: 'PATIENT_ID' }, doctor_id: { type: DataTypes.INTEGER, allowNull: false, field: 'DOCTOR_ID' }, department_id: { type: DataTypes.INTEGER, allowNull: false, field: 'DEPARTMENT_ID' }, token_number: { type: DataTypes.INTEGER, allowNull: false, field: 'TOKEN_NUMBER' }, token_date: { type: DataTypes.DATEONLY, allowNull: false, field: 'TOKEN_DATE' }, status: { type: DataTypes.STRING(20), field: 'STATUS' }, generated_by: { type: DataTypes.INTEGER, field: 'GENERATED_BY' } }, { tableName: 'HMS_TOKENS', freezeTableName: true, timestamps: false });
  return { Department, Doctor, Appointment, Token };
}
module.exports = { createModels };
