const express = require('express');
const { Op, QueryTypes } = require('sequelize');

const SLOTS = ['09:00','09:15','09:30','09:45','10:00','10:15','10:30','10:45','11:00','11:15','11:30','11:45','12:00','12:15','12:30','12:45','14:00','14:15','14:30','14:45','15:00','15:15','15:30','15:45'];
function endSlot(start) { const [h,m] = String(start).split(':').map(Number); if (!Number.isFinite(h) || !Number.isFinite(m)) return null; const total = h * 60 + m + 15; return `${String(Math.floor(total / 60)).padStart(2,'0')}:${String(total % 60).padStart(2,'0')}`; }
function status(value) { const key = String(value || '').trim().toLowerCase().replace(/[\s_-]+/g,''); return ({ scheduled:'Scheduled', checkedin:'Checked-in', completed:'Completed', cancelled:'Cancelled', canceled:'Cancelled', noshow:'No Show' })[key] || value || 'Scheduled'; }
function createRoutes(models, sequelize, config) {
  const { Department, Doctor, Appointment, Token } = models; const router = express.Router();
  async function nextval(sequence) { const [[row]] = await sequelize.query(`SELECT nextval('${sequence}') AS id`); return Number(row.id); }
  async function audit(req, action, module, recordId, newValue) { const response = await fetch(`${config.identityUrl}/internal/v1/audit`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-internal-service-token': config.internalServiceSecret, 'idempotency-key': `opd:${req.id}` }, body: JSON.stringify({ userId: req.user.id, action, module, recordId, newValue }), signal: AbortSignal.timeout(config.requestTimeoutMs) }); if (!response.ok) { const error = new Error(`audit service returned ${response.status}`); error.status = 503; throw error; } }
  async function internal(url, options = {}) { const response = await fetch(url, { ...options, headers: { ...(options.headers || {}), 'x-internal-service-token': config.internalServiceSecret }, signal: AbortSignal.timeout(config.requestTimeoutMs) }); if (!response.ok) { const error = new Error(`internal dependency returned ${response.status}`); error.status = response.status; throw error; } return response.json(); }
  async function patient(id, required = true) { try { return await internal(`${config.patientUrl}/internal/v1/patients/${Number(id)}`); } catch (error) { if (!required && error.status === 404) return { data: null }; throw error; } }
  async function user(id) { return internal(`${config.identityUrl}/internal/v1/users/${Number(id)}`); }
  async function resolveDoctor(id) { return Doctor.findOne({ where: { [Op.or]: [{ id }, { user_id: id }], is_active: 'Y' } }); }
  async function departmentExists(id) { return Department.findOne({ where: { id, is_active: 'Y' } }); }
  async function enrichAppointment(row) { const [p, d, dept, doctorUser] = await Promise.all([patient(row.patient_id, false), Doctor.findByPk(row.doctor_id), Department.findByPk(row.department_id), Doctor.findByPk(row.doctor_id).then((x) => x ? user(x.user_id) : null)]); return { id: row.id, appointment_date: row.appointment_date, slot_start: row.slot_start, slot_end: row.slot_end, appointment_time: row.slot_start, appt_type: row.appt_type, status: row.status, cancellation_reason: row.cancellation_reason, booked_by: row.booked_by, patient: p.data, doctor: { id: row.doctor_id, speciality: d?.speciality, name: doctorUser?.data?.name, user: { name: doctorUser?.data?.name } }, department: { id: row.department_id, name: dept?.name } }; }

  router.get('/api/hms/departments', async (req, res, next) => { try { return res.json({ success: true, data: await Department.findAll({ where: { is_active: 'Y' }, order: [['name','ASC']] }) }); } catch (e) { next(e); } });
  router.post('/api/hms/departments', async (req, res, next) => { try { if (!req.body.name) return res.status(400).json({ success: false, message: 'Name required.' }); const id = await nextval('hms_department_seq').catch(async () => { const [[row]] = await sequelize.query('SELECT COALESCE(MAX(ID), 0) + 1 AS id FROM HMS_DEPARTMENTS'); return Number(row.id); }); const dept = await Department.create({ id, name: req.body.name, short_code: req.body.short_code || null, floor_location: req.body.floor_location || null, is_active: 'Y' }); await audit(req, 'CREATE', 'department', dept.id, { name: dept.name }); return res.status(201).json({ success: true, data: dept }); } catch (e) { next(e); } });
  router.get('/api/hms/departments/:id/doctors', async (req, res, next) => { try { const doctors = await Doctor.findAll({ where: { department_id: req.params.id, is_active: 'Y' } }); const data = await Promise.all(doctors.map(async (d) => ({ ...d.toJSON(), user: (await user(d.user_id)).data }))); return res.json({ success: true, data }); } catch (e) { next(e); } });
  router.get('/api/hms/doctors', async (req, res, next) => { try { const identity = await internal(`${config.identityUrl}/internal/v1/users?role=doctor`); const users = identity.data || []; const ids = users.map((u) => u.id); const doctors = ids.length ? await Doctor.findAll({ where: { user_id: { [Op.in]: ids }, is_active: 'Y' } }) : []; const byUser = new Map(doctors.map((d) => [d.user_id, d])); return res.json({ success: true, data: users.map((u) => { const d = byUser.get(u.id); return { id: d?.id || u.id, user_id: u.id, doctor_id: d?.id || null, speciality: d?.speciality || 'General', user: { name: u.name, phone: u.phone } }; }) }); } catch (e) { next(e); } });
  router.get('/api/hms/doctors/:id', async (req, res, next) => { try { const d = await resolveDoctor(req.params.id); if (!d) return res.status(404).json({ success: false, message: 'Doctor not found.' }); const [u, dept] = await Promise.all([user(d.user_id), Department.findByPk(d.department_id)]); return res.json({ success: true, data: { ...d.toJSON(), user: u.data, department: dept ? { name: dept.name } : null } }); } catch (e) { next(e); } });
  router.post('/api/hms/doctors', async (req, res, next) => { try { if (!req.body.user_id) return res.status(400).json({ success: false, message: 'user_id required.' }); const d = await Doctor.create({ id: await nextval('hms_doctor_seq'), user_id: req.body.user_id, department_id: req.body.department_id || null, speciality: req.body.speciality || null, registration_number: req.body.registration_number || null, fee: req.body.fee || 0, slot_duration_mins: req.body.slot_duration_mins || 15, is_active: 'Y' }); await audit(req, 'CREATE', 'doctor', d.id, { user_id: d.user_id, department_id: d.department_id }); return res.status(201).json({ success: true, data: d }); } catch (e) { next(e); } });

  router.post('/api/hms/appointments', async (req, res, next) => { try { const { patient_id, doctor_id, department_id, appointment_date } = req.body; if (!patient_id || !doctor_id || !department_id || !appointment_date) return res.status(400).json({ success: false, message: 'patient_id, doctor_id, department_id, and appointment_date are required.' }); await patient(patient_id); const doctor = await resolveDoctor(doctor_id); if (!doctor || !(await departmentExists(department_id))) return res.status(400).json({ success: false, message: 'Doctor or department not found.' }); const result = await sequelize.transaction(async (transaction) => { await sequelize.query("SELECT pg_advisory_xact_lock(hashtext(:lockKey))", { replacements: { lockKey: `appointment:${doctor.id}:${appointment_date}` }, transaction }); const booked = await Appointment.findAll({ where: { doctor_id: doctor.id, appointment_date, status: { [Op.notIn]: ['Cancelled','Completed','No Show'] } }, attributes: ['slot_start'], transaction }); const requested = req.body.slot_start || req.body.appointment_time; const slot = requested || SLOTS.find((candidate) => !booked.some((x) => x.slot_start === candidate)); if (!slot || booked.some((x) => x.slot_start === slot)) { const e = new Error('This slot is already booked or no slots are available.'); e.status = 400; throw e; } return Appointment.create({ id: await nextval('hms_appt_seq'), patient_id: Number(patient_id), doctor_id: doctor.id, department_id: Number(department_id), appointment_date, slot_start: slot, slot_end: req.body.slot_end || endSlot(slot), appt_type: req.body.appt_type || 'walk-in', status: status(req.body.status), booked_by: req.user.id }, { transaction }); }); await audit(req, 'CREATE', 'appointment', result.id, { date: result.appointment_date, slot: result.slot_start }); return res.status(201).json({ success: true, message: 'Appointment booked.', data: result }); } catch (e) { next(e); } });
  router.get('/api/hms/appointments', async (req, res, next) => { try { const where = {}; for (const key of ['doctor_id','department_id','patient_id','status']) if (req.query[key]) where[key] = req.query[key]; if (req.query.date) where.appointment_date = req.query.date; const rows = await Appointment.findAll({ where, order: [['appointment_date','DESC'],['slot_start','ASC']] }); const data = await Promise.all(rows.map(enrichAppointment)); return res.json({ success: true, data }); } catch (e) { next(e); } });
  router.put('/api/hms/appointments/:id', async (req, res, next) => { try { const a = await Appointment.findByPk(req.params.id); if (!a) return res.status(404).json({ success: false, message: 'Appointment not found.' }); const nextDate = req.body.appointment_date || a.appointment_date; const requested = req.body.slot_start || req.body.appointment_time || a.slot_start; if (nextDate !== String(a.appointment_date) || requested !== a.slot_start) { const conflict = await Appointment.findOne({ where: { id: { [Op.ne]: a.id }, doctor_id: a.doctor_id, appointment_date: nextDate, slot_start: requested, status: { [Op.notIn]: ['Cancelled','Completed','No Show'] } } }); if (conflict) return res.status(400).json({ success: false, message: 'This slot is already booked.' }); } await a.update({ appointment_date: nextDate, slot_start: requested, slot_end: req.body.slot_end || endSlot(requested), status: status(req.body.status || a.status), cancellation_reason: req.body.cancellation_reason || a.cancellation_reason }); await audit(req, 'UPDATE', 'appointment', a.id, { date: a.appointment_date, slot: a.slot_start, status: a.status }); return res.json({ success: true, data: a }); } catch (e) { next(e); } });

  router.post('/api/hms/tokens', async (req, res, next) => { try { const { patient_id, doctor_id, department_id } = req.body; if (!patient_id || !doctor_id || !department_id) return res.status(400).json({ success: false, message: 'Missing required fields.' }); await patient(patient_id); const doctor = await resolveDoctor(doctor_id); if (!doctor || !(await departmentExists(department_id))) { const e = new Error('Doctor or department not found.'); e.status = 400; throw e; } const today = new Date().toISOString().slice(0,10); const token = await sequelize.transaction(async (transaction) => { await sequelize.query("SELECT pg_advisory_xact_lock(hashtext(:lockKey))", { replacements: { lockKey: `token:${doctor.id}:${today}` }, transaction }); const max = await Token.max('token_number', { where: { doctor_id: doctor.id, token_date: today }, transaction }); return Token.create({ id: await nextval('hms_token_seq'), patient_id: Number(patient_id), doctor_id: doctor.id, department_id: Number(department_id), token_date: today, token_number: Number(max || 0) + 1, status: 'Waiting', generated_by: req.user.id }, { transaction }); }); await audit(req, 'CREATE', 'token', token.id, { token_number: token.token_number }); return res.status(201).json({ success: true, message: 'Token generated successfully.', data: token }); } catch (e) { next(e); } });
  router.get('/api/hms/tokens/queue', async (req, res, next) => { try { const where = { token_date: req.query.date || new Date().toISOString().slice(0,10) }; if (req.query.doctor_id) where.doctor_id = req.query.doctor_id; const rows = await Token.findAll({ where, order: [['token_number','ASC']] }); const data = await Promise.all(rows.map(async (t) => ({ ...t.toJSON(), patient: (await patient(t.patient_id, false)).data }))); return res.json({ success: true, data }); } catch (e) { next(e); } });
  router.get('/api/hms/tokens/today-all', async (req, res, next) => { try { const rows = await Token.findAll({ where: { token_date: new Date().toISOString().slice(0,10) }, order: [['token_number','ASC']] }); const data = await Promise.all(rows.map(async (t) => ({ ...t.toJSON(), patient: (await patient(t.patient_id)).data }))); return res.json({ success: true, data }); } catch (e) { next(e); } });
  router.get('/api/hms/tokens', async (req, res, next) => { try { const today = new Date().toISOString().slice(0,10); const currentDoctor = req.user.role === 'doctor' ? await resolveDoctor(req.user.id) : null; const rows = await Token.findAll({ where: { token_date: today, ...(currentDoctor ? { doctor_id: currentDoctor.id } : {}) }, order: [['token_number','ASC']] }); return res.json({ success: true, data: rows }); } catch (e) { next(e); } });
  router.patch('/api/hms/tokens/:id/status', async (req, res, next) => { try { const t = await Token.findByPk(req.params.id); if (!t) return res.status(404).json({ success: false, message: 'Token not found.' }); await t.update({ status: req.body.status }); await audit(req, 'UPDATE', 'token_status', t.id, { status: t.status }); return res.json({ success: true, message: 'Status updated.', data: t }); } catch (e) { next(e); } });
  return router;
}
module.exports = { createRoutes };
