const express = require('express');
const { Op } = require('sequelize');

const TYPES = new Set(['corporate_employee', 'cisf_employee', 'other']);
const PHONE_TYPES = new Set(['other']);
function splitName(value) { const parts = String(value || '').trim().replace(/\s+/g, ' ').split(' ').filter(Boolean); return { first_name: parts[0] || null, last_name: parts.slice(1).join(' ') || null }; }
function clean(value) { return value === undefined || value === null || String(value).trim() === '' ? null : String(value).trim(); }
function core(req, existing = {}) {
  const b = req.body || {}; const patientType = b.patientType ?? existing.patientType; const name = b.name ?? existing.name;
  if (!patientType || !name || b.age === undefined && existing.age === undefined || !b.gender && !existing.gender || !b.opdIndoor && !existing.opdIndoor || !b.testDate && !existing.testDate) throw Object.assign(new Error('Required core fields missing.'), { status: 400 });
  if (!TYPES.has(patientType)) throw Object.assign(new Error('Invalid patient type.'), { status: 400 });
  const phone = b.phoneNumber === undefined ? existing.phoneNumber : clean(b.phoneNumber);
  if (PHONE_TYPES.has(patientType) && (!phone || !/^\d{10}$/.test(phone))) throw Object.assign(new Error('Valid 10-digit Phone Number is required.'), { status: 400 });
  if (patientType === 'corporate_employee' && !(b.empNumber || existing.empNumber)) throw Object.assign(new Error('Employee number is required for corporate employees.'), { status: 400 });
  const names = splitName(name); return { patientType, name, age: Number(b.age ?? existing.age), gender: b.gender ?? existing.gender, opdIndoor: b.opdIndoor ?? existing.opdIndoor, ward: b.ward ?? existing.ward ?? 'N/A', testDate: b.testDate ?? existing.testDate, provDiagnosis: clean(b.provDiagnosis ?? existing.provDiagnosis), empNumber: patientType === 'other' ? null : clean(b.empNumber ?? existing.empNumber), relationship: patientType === 'corporate_employee' ? (clean(b.relationship ?? existing.relationship) || 'Self') : null, phoneNumber: phone, ...names, dob: clean(b.dob), blood_group: clean(b.blood_group), alt_phone: clean(b.alt_phone), email: clean(b.email), house_no: clean(b.house_no), street: clean(b.street), city: clean(b.city), state: clean(b.state), pin: clean(b.pin), country: clean(b.country) || 'India', emergency_contact_name: clean(b.emergency_contact_name), emergency_contact_relation: clean(b.emergency_contact_relation), emergency_contact_phone: clean(b.emergency_contact_phone), aadhaar: clean(b.aadhaar), photo_url: clean(b.photo_url) };
}

function createRoutes(models, sequelize, config) {
  const { Patient, Allergy, ChronicCondition, PatientDocument } = models; const router = express.Router();
  const find = (id) => Patient.findByPk(id);
  const register = async (req, res, next) => { try { const data = core(req); const [[seq]] = await sequelize.query("SELECT nextval('hms_patients_seq') AS id"); const id = Number(seq.id); const patient = await Patient.create({ ...data, id, uhid: `HOSP-${new Date().getFullYear()}-${String(id).padStart(6, '0')}`, registeredBy: req.user.id, is_active: 1, createdAt: new Date(), updatedAt: new Date() }); let reportId = null; if (config.monolithUrl) { try { const response = await fetch(`${config.monolithUrl}/internal/compat/test-reports`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-internal-service-token': config.internalServiceSecret, 'x-request-id': req.id }, body: JSON.stringify({ patientId: id, reportedBy: req.user.id }), signal: AbortSignal.timeout(config.serviceRequestTimeoutMs) }); if (!response.ok) throw new Error(`lab compatibility returned ${response.status}`); const payload = await response.json(); reportId = payload.reportId; } catch (error) { await patient.destroy(); throw Object.assign(new Error('Patient registration could not initialize its lab report.'), { status: 503, cause: error }); } } return res.status(201).json({ success: true, message: 'Patient registered.', data: patient.toJSON(), patient: { id, uhid: patient.uhid }, reportId }); } catch (e) { next(e); } };
  router.post('/', register);
  router.post('/hms', register);
  router.get('/', async (req, res, next) => { try { const where = {}; if (req.query.patientType) where.patientType = req.query.patientType; if (req.query.empNumber) where.empNumber = { [Op.iLike]: `%${req.query.empNumber}%` }; if (req.query.phoneNumber) where.phoneNumber = { [Op.iLike]: `%${req.query.phoneNumber}%` }; const all = await Patient.findAll({ where, order: [['createdAt', 'DESC']] }); const page = Math.max(1, Number(req.query.page || 1)); const limit = Math.min(100, Math.max(1, Number(req.query.limit || 20))); return res.json({ success: true, total: all.length, page, patients: all.slice((page - 1) * limit, page * limit) }); } catch (e) { next(e); } });
  router.get('/hms/search', async (req, res, next) => { try { const q = clean(req.query.q); const where = {}; if (q) where[Op.or] = [{ name: { [Op.iLike]: `%${q}%` } }, { uhid: { [Op.iLike]: `%${q}%` } }, { phoneNumber: { [Op.iLike]: `%${q}%` } }, { empNumber: { [Op.iLike]: `%${q}%` } }, { relationship: { [Op.iLike]: `%${q}%` } }]; if (req.query.patientType) where.patientType = req.query.patientType; if (req.query.empNumber) where.empNumber = { [Op.iLike]: `%${req.query.empNumber}%` }; if (req.query.phoneNumber) where.phoneNumber = { [Op.iLike]: `%${req.query.phoneNumber}%` }; const patients = await Patient.findAll({ where, order: [['createdAt', 'DESC']] }); return res.json({ success: true, data: patients.map((p) => ({ id: p.id, uhid: p.uhid, patient_name: p.name, first_name: p.first_name, last_name: p.last_name, age: p.age, gender: p.gender, patient_type: p.patientType, emp_number: p.empNumber, relationship: p.relationship, phone_number: p.phoneNumber, registration_date: p.createdAt })) }); } catch (e) { next(e); } });
  router.get('/hms/today-patients', async (req, res, next) => { try { const rows = await Patient.findAll({ where: sequelize.where(sequelize.fn('DATE', sequelize.col('CREATED_AT')), '=', sequelize.literal('CURRENT_DATE')), order: [['createdAt', 'DESC']] }); return res.json({ success: true, data: rows.map((p) => ({ ...p.toJSON(), encounter_id: null, consulting_doctor_id: null, consulting_doctor_name: null, encounter_status: null })) }); } catch (e) { next(e); } });
  router.get('/hms/pending-consultation', async (req, res, next) => { try { const rows = await Patient.findAll({ where: sequelize.where(sequelize.fn('DATE', sequelize.col('CREATED_AT')), '<', sequelize.literal('CURRENT_DATE')), order: [['createdAt', 'DESC']] }); return res.json({ success: true, data: rows.map((p) => ({ ...p.toJSON(), days_ago: Math.max(0, Math.floor((Date.now() - new Date(p.createdAt).getTime()) / 86400000)) })) }); } catch (e) { next(e); } });
  const corporateLookup = async (req, res, next) => { try { const rows = await Patient.findAll({ where: { empNumber: { [Op.iLike]: `%${String(req.params.empNumber).replace(/\D/g, '')}%` } }, order: [['relationship', 'ASC'], ['createdAt', 'ASC']] }); return res.json({ success: true, data: rows.map((p) => ({ name: p.name, age: p.age, gender: p.gender, relationship: p.relationship || 'Other' })) }); } catch (e) { next(e); } };
  router.get('/hms/emp/:empNumber', corporateLookup);
  router.get('/hms/corporate/:empNumber', corporateLookup);
  router.get('/hms/:id/documents', async (req, res, next) => { try { return res.json({ success: true, data: await PatientDocument.findAll({ where: { patient_id: req.params.id }, order: [['uploaded_at', 'DESC']] }) }); } catch (e) { next(e); } });
  router.get('/hms/:id/allergies', async (req, res, next) => { try { return res.json({ success: true, data: await Allergy.findAll({ where: { patient_id: req.params.id }, order: [['noted_at', 'DESC']] }) }); } catch (e) { next(e); } });
  router.get('/hms/:id/chronic-conditions', async (req, res, next) => { try { return res.json({ success: true, data: await ChronicCondition.findAll({ where: { patient_id: req.params.id }, order: [['created_at', 'DESC']] }) }); } catch (e) { next(e); } });
  router.post('/hms/:id/allergies', async (req, res, next) => { try { if (!req.body.allergen) return res.status(400).json({ success: false, message: 'Allergen is required.' }); const [[allergySeq]] = await sequelize.query("SELECT nextval('hms_allergy_seq') AS id"); return res.status(201).json({ success: true, data: await Allergy.create({ id: Number(allergySeq.id), patient_id: req.params.id, allergen: req.body.allergen, reaction: req.body.reaction || null, severity: req.body.severity || null, noted_by: req.user.id, noted_at: new Date() }) }); } catch (e) { next(e); } });
  router.post('/hms/:id/chronic-conditions', async (req, res, next) => { try { if (!req.body.condition_name) return res.status(400).json({ success: false, message: 'Condition name required.' }); const [[chronicSeq]] = await sequelize.query("SELECT nextval('hms_chronic_seq') AS id"); return res.status(201).json({ success: true, data: await ChronicCondition.create({ id: Number(chronicSeq.id), patient_id: req.params.id, condition_name: req.body.condition_name, since_when: req.body.since_when || null, notes: req.body.notes || null, created_at: new Date() }) }); } catch (e) { next(e); } });
  router.get('/hms/:id', async (req, res, next) => { try { const patient = await find(req.params.id); if (!patient) return res.status(404).json({ success: false, message: 'Patient not found.' }); const [allergies, chronic_conditions] = await Promise.all([Allergy.findAll({ where: { patient_id: patient.id } }), ChronicCondition.findAll({ where: { patient_id: patient.id } })]); return res.json({ success: true, data: { ...patient.toJSON(), counts: { lab_reports: 0, visits: 0, prescriptions: 0 }, allergies, chronic_conditions } }); } catch (e) { next(e); } });
  router.put('/:id', async (req, res, next) => { try { const patient = await find(req.params.id); if (!patient) return res.status(404).json({ success: false, message: 'Patient not found.' }); const data = core(req, patient.toJSON()); await patient.update(data); return res.json({ success: true, message: 'Patient updated successfully.', patient }); } catch (e) { next(e); } });
  router.get('/:id', async (req, res, next) => { try { const patient = await find(req.params.id); if (!patient) return res.status(404).json({ success: false, message: 'Patient not found.' }); return res.json({ success: true, patient, report: null }); } catch (e) { next(e); } });
  router.delete('/:id', async (req, res, next) => { try { if (req.user?.role !== 'super_admin') return res.status(403).json({ success: false, message: 'Insufficient role.' }); const patient = await find(req.params.id); if (!patient) return res.status(404).json({ success: false, message: 'Patient not found' }); if (config.monolithUrl) { const reportResponse = await fetch(`${config.monolithUrl}/internal/compat/test-reports/${patient.id}`, { method: 'DELETE', headers: { 'x-internal-service-token': config.internalServiceSecret, 'x-request-id': req.id }, signal: AbortSignal.timeout(config.serviceRequestTimeoutMs) }); if (!reportResponse.ok && reportResponse.status !== 404) throw Object.assign(new Error('Lab report cleanup unavailable.'), { status: 503 }); } await sequelize.transaction(async (transaction) => { await Promise.all([Allergy.destroy({ where: { patient_id: patient.id }, transaction }), ChronicCondition.destroy({ where: { patient_id: patient.id }, transaction }), PatientDocument.destroy({ where: { patient_id: patient.id }, transaction })]); await patient.destroy({ transaction }); }); return res.json({ success: true, message: 'Patient record successfully deleted.' }); } catch (e) { next(e); } });
  return router;
}
module.exports = { createRoutes };
