ALTER TABLE HMS_AUDIT_LOGS
  ADD COLUMN IF NOT EXISTS IDEMPOTENCY_KEY VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS UX_HMS_AUDIT_LOGS_IDEMPOTENCY_KEY
  ON HMS_AUDIT_LOGS (IDEMPOTENCY_KEY)
  WHERE IDEMPOTENCY_KEY IS NOT NULL;
